{
  imports = [
    ./gnome
    ./virtualisation
    ./amdgpu.nix
    ./appimage.nix
    ./audio.nix
    ./bluetooth.nix
    ./boot.nix
    ./docker.nix
    ./env.nix
    ./flatpak.nix
    ./fprintd.nix
    ./git.nix
    ./gnupg.nix
    ./i18n.nix
    ./java.nix
    ./kernel.nix
    ./network.nix
    ./pakages.nix
    ./shell.nix
    ./time.nix
    ./users.nix
    ./zram.nix
  ];
}
